apiVersion: v1
kind: PersistentVolume
metadata:
  name: ragline-data-pv
  namespace: ragline
  labels:
    app.kubernetes.io/name: ragline
    app.kubernetes.io/managed-by: kubectl
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/ragline
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ragline-data-pvc
  namespace: ragline
  labels:
    app.kubernetes.io/name: ragline
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-models-pv
  namespace: ragline
  labels:
    app.kubernetes.io/name: ragline
    app.kubernetes.io/managed-by: kubectl
    component: llm-models
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/ragline/models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models-pvc
  namespace: ragline
  labels:
    app.kubernetes.io/name: ragline
    app.kubernetes.io/managed-by: kubectl
    component: llm-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

