{{- if and .Values.global.createGhcrPullSecret .Values.secrets.ghcrUsername .Values.secrets.ghcrToken }}
{{- $name := "ghcr-secret" }}
{{- if and .Values.global.imagePullSecrets (gt (len .Values.global.imagePullSecrets) 0) }}
{{- $name = (index .Values.global.imagePullSecrets 0).name }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "ragline.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "ragline.dockerconfigjson" . }}
{{- end }}
