apiVersion: v1
kind: Secret
metadata:
  name: ragline-secrets
  labels:
    {{- include "ragline.labels" . | nindent 4 }}
type: Opaque
data:
  # Azure DevOps PAT
  {{- if .Values.secrets.azureDevOpsPat }}
  AZURE_DEVOPS_PAT: {{ .Values.secrets.azureDevOpsPat | b64enc }}
  {{- end }}
  
  # M365 credentials
  {{- if .Values.secrets.m365TenantId }}
  M365_TENANT_ID: {{ .Values.secrets.m365TenantId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.m365ClientId }}
  M365_CLIENT_ID: {{ .Values.secrets.m365ClientId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.m365ClientSecret }}
  M365_CLIENT_SECRET: {{ .Values.secrets.m365ClientSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.m365Username }}
  M365_USERNAME: {{ .Values.secrets.m365Username | b64enc }}
  {{- end }}
  {{- if .Values.secrets.m365Password }}
  M365_PASSWORD: {{ .Values.secrets.m365Password | b64enc }}
  {{- end }}
  {{- if .Values.secrets.m365SharepointHost }}
  M365_SHAREPOINT_HOST: {{ .Values.secrets.m365SharepointHost | b64enc }}
  {{- end }}
  {{- if .Values.secrets.m365SitePath }}
  M365_SITE_PATH: {{ .Values.secrets.m365SitePath | b64enc }}
  {{- end }}
  
  # GitHub PAT
  {{- if .Values.secrets.githubPat }}
  GITHUB_PAT: {{ .Values.secrets.githubPat | b64enc }}
  {{- end }}
  
  # AI Service Keys
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiApiKey }}
  AZURE_OPENAI_API_KEY: {{ .Values.secrets.azureOpenaiApiKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiEndpoint }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.secrets.azureOpenaiEndpoint | b64enc }}
  {{- end }}
  
  # Entra ID Client Secret
  {{- if .Values.secrets.entraIdClientSecret }}
  ENTRA_ID_CLIENT_SECRET: {{ .Values.secrets.entraIdClientSecret | b64enc }}
  {{- end }}
---
{{- if or .Values.services.adoMcp.enabled .Values.services.githubMcp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ragline-mcp-secrets
  labels:
    {{- include "ragline.labels" . | nindent 4 }}
    component: mcp-secrets
type: Opaque
data:
  # Azure DevOps MCP credentials
  {{- if .Values.secrets.azureDevOpsOrg }}
  AZDO_ORG: {{ .Values.secrets.azureDevOpsOrg | b64enc }}
  {{- end }}
  {{- if .Values.secrets.azureDevOpsToken }}
  AZDO_TOKEN: {{ .Values.secrets.azureDevOpsToken | b64enc }}
  {{- end }}
  
  # GitHub MCP credentials
  {{- if .Values.secrets.githubToken }}
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | b64enc }}
  {{- end }}
{{- end }}
---
{{- if .Values.config.auth.entraId.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ragline-entra-secret
  labels:
    {{- include "ragline.labels" . | nindent 4 }}
    component: entra-auth
type: Opaque
data:
  {{- if .Values.secrets.entraIdClientSecret }}
  client-secret: {{ .Values.secrets.entraIdClientSecret | b64enc }}
  {{- end }}
{{- end }}
